/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConnectorsRouteImport } from './routes/admin.connectors'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminProvidersRouteImport } from './routes/admin.providers'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as DashboardConnectionsRouteImport } from './routes/dashboard.connections'
import { Route as DashboardCreditsRouteImport } from './routes/dashboard.credits'
import { Route as DashboardDownloadRouteImport } from './routes/dashboard.download'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardSubscriptionRouteImport } from './routes/dashboard.subscription'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConnectorsRoute = AdminConnectorsRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardConnectionsRoute = DashboardConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreditsRoute = DashboardCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDownloadRoute = DashboardDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionRoute = DashboardSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/connectors': typeof AdminConnectorsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/connectors': typeof AdminConnectorsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/connectors': typeof AdminConnectorsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/connections': typeof DashboardConnectionsRoute
  '/dashboard/credits': typeof DashboardCreditsRoute
  '/dashboard/download': typeof DashboardDownloadRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/subscription': typeof DashboardSubscriptionRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/connectors'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/roles'
    | '/admin/users'
    | '/dashboard/connections'
    | '/dashboard/credits'
    | '/dashboard/download'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/subscription'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/connectors'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/roles'
    | '/admin/users'
    | '/dashboard/connections'
    | '/dashboard/credits'
    | '/dashboard/download'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/subscription'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/connectors'
    | '/admin/coupons'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/plans'
    | '/admin/pricing'
    | '/admin/providers'
    | '/admin/roles'
    | '/admin/users'
    | '/dashboard/connections'
    | '/dashboard/credits'
    | '/dashboard/download'
    | '/dashboard/notifications'
    | '/dashboard/payments'
    | '/dashboard/profile'
    | '/dashboard/subscription'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/connectors': {
      id: '/admin/connectors'
      path: '/connectors'
      fullPath: '/admin/connectors'
      preLoaderRoute: typeof AdminConnectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/connections': {
      id: '/dashboard/connections'
      path: '/connections'
      fullPath: '/dashboard/connections'
      preLoaderRoute: typeof DashboardConnectionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/credits': {
      id: '/dashboard/credits'
      path: '/credits'
      fullPath: '/dashboard/credits'
      preLoaderRoute: typeof DashboardCreditsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/download': {
      id: '/dashboard/download'
      path: '/download'
      fullPath: '/dashboard/download'
      preLoaderRoute: typeof DashboardDownloadRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscription': {
      id: '/dashboard/subscription'
      path: '/subscription'
      fullPath: '/dashboard/subscription'
      preLoaderRoute: typeof DashboardSubscriptionRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConnectorsRoute: typeof AdminConnectorsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConnectorsRoute: AdminConnectorsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardConnectionsRoute: typeof DashboardConnectionsRoute
  DashboardCreditsRoute: typeof DashboardCreditsRoute
  DashboardDownloadRoute: typeof DashboardDownloadRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSubscriptionRoute: typeof DashboardSubscriptionRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardConnectionsRoute: DashboardConnectionsRoute,
  DashboardCreditsRoute: DashboardCreditsRoute,
  DashboardDownloadRoute: DashboardDownloadRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSubscriptionRoute: DashboardSubscriptionRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
